ARG PHP_VERSION=8.4
ARG COMPOSER_VERSION=2.8

FROM composer:${COMPOSER_VERSION} AS composer_builder
FROM php:${PHP_VERSION}-fpm-alpine

LABEL maintainer="Yazo Labs <contato@yazolabs.com.br>"

COPY --from=composer_builder /usr/bin/composer /usr/local/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_PROCESS_TIMEOUT=900 \
    COMPOSER_DISABLE_XDEBUG_WARN=1

ENV XDEBUG_IDEKEY=xdebug \
    XDEBUG_CLIENT_HOST=host.docker.internal \
    XDEBUG_CLIENT_PORT=9003 \
    XDEBUG_MODE=off \
    XDEBUG_START_WITH_REQUEST=off

COPY docker/php/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

RUN apk add --no-cache \
    libc-dev \
    libpng-dev \
    libzip-dev \
    linux-headers \
    openjdk8 \
    postgresql17-client \
    postgresql-dev \
    ttf-dejavu \
    unzip \
    openssh \
    git \
    curl \
    bash \
    nodejs-current \
    npm

RUN apk add --no-cache --virtual .phpize_deps $PHPIZE_DEPS && \
    pecl install redis xdebug && \
    docker-php-ext-enable redis xdebug && \
    docker-php-ext-install bcmath gd pcntl pdo pdo_pgsql pgsql zip ftp && \
    apk del .phpize_deps

RUN addgroup -g ${HOST_GID} ieducar 2>/dev/null || true && \
    adduser -u ${HOST_UID} -G ieducar -s /bin/sh -D ieducar 2>/dev/null || true

WORKDIR /var/www/ieducar
