x-php: &php
  build:
    context: .
    dockerfile: docker/php/Dockerfile.dev
    args:
      PHP_VERSION: 8.4
      COMPOSER_VERSION: 2.8
      HOST_UID: ${HOST_UID:-1001}
      HOST_GID: ${HOST_GID:-1001}
  working_dir: /var/www/ieducar
  links:
    - postgres
    - redis
  environment:
    CACHE_DRIVER: redis
    REDIS_HOST: redis
    DB_HOST: postgres
    PGPASSWORD: ${DB_PASSWORD}
  extra_hosts:
    - host.docker.internal:host-gateway

services:
  php:
    <<: *php
    container_name: siduc-php
    command: tail -f /dev/null
    restart: none
    volumes:
      - ./:/var/www/ieducar
    networks:
      - siduc-dev

  fpm:
    <<: *php
    container_name: siduc-fpm
    command: php-fpm
    restart: none
    volumes:
      - ./:/var/www/ieducar
    networks:
      - siduc-dev

  horizon:
    <<: *php
    container_name: siduc-horizon
    command: php /var/www/ieducar/artisan horizon
    restart: none
    volumes:
      - ./:/var/www/ieducar
    networks:
      - siduc-dev

  nginx:
    container_name: siduc-nginx
    image: nginx:1.28-alpine
    working_dir: /var/www/ieducar
    volumes:
      - ./:/var/www/ieducar
      - ./docker/nginx/conf.d/dev:/etc/nginx/conf.d/
      - ./docker/nginx/snippets/dev:/etc/nginx/snippets/
    ports:
      - "80:80"
    depends_on:
      - fpm
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost || true"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - siduc-dev

  postgres:
    container_name: siduc-postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_USERNAME}
    volumes:
      - ieducar_postgres_data:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    networks:
      - siduc-dev

  redis:
    container_name: siduc-redis
    image: redis:8-alpine
    restart: none
    ports:
      - ${DOCKER_REDIS_PORT:-6379}:6379
    networks:
      - siduc-dev

  pmd:
    container_name: siduc-pmd
    image: node:22-alpine
    command: sh -lc "yarn install && yarn dev --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./packages/portabilis/pre-matricula-digital:/var/www/pre-matricula-digital
    working_dir: /var/www/pre-matricula-digital
    networks:
      - siduc-dev

volumes:
  ieducar_postgres_data:

networks:
  siduc-dev:
    external: true
