x-php: &php
  build:
    context: docker/php
    args:
      PHP_VERSION: 8.4
      COMPOSER_VERSION: 2.8
      HOST_UID: ${HOST_UID:-1001}
      HOST_GID: ${HOST_GID:-1001}
  image: php:8.4-ieducar
  working_dir: /var/www/ieducar
  volumes:
    - /data/coolify/applications/${COOLIFY_APP_ID:-nwww8scccc84c04s0okck8kg}/app:/var/www/ieducar-app
  links:
    - postgres
    - redis
  depends_on:
    postgres:
      condition: service_started
    redis:
      condition: service_started
  environment:
    CACHE_DRIVER: redis
    REDIS_HOST: redis
    DB_HOST: postgres
    PGPASSWORD: ${DB_PASSWORD}
  extra_hosts:
    - host.docker.internal:host-gateway

services:
  php:
    <<: *php
    container_name: ieducar-php
    command: sh -c "cp -r /var/www/ieducar-app/* /var/www/ieducar && tail -f /dev/null"

  fpm:
    <<: *php
    container_name: ieducar-fpm
    command: sh -c "cp -r /var/www/ieducar-app/* /var/www/ieducar && php-fpm"

  horizon:
    <<: *php
    container_name: ieducar-horizon
    command: sh -c 'cp -r /var/www/ieducar-app/* /var/www/ieducar && php /var/www/ieducar/artisan horizon'
    restart: always

  nginx:
    container_name: ieducar-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - fpm
    working_dir: /var/www/ieducar
    volumes:
      - /data/coolify/applications/${COOLIFY_APP_ID:-nwww8scccc84c04s0okck8kg}/app:/var/www/ieducar-app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/snippets:/etc/nginx/snippets/
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  postgres:
    container_name: ieducar-postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_USERNAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${DOCKER_POSTGRES_PORT:-5432}:5432

  redis:
    container_name: ieducar-redis
    image: redis:8-alpine
    restart: always
    ports:
      - ${DOCKER_REDIS_PORT:-6379}:6379

volumes:
  postgres:
