FROM nginx:1.28-alpine

RUN apk add --no-cache curl

COPY ./docker/nginx/conf.d/prod/default.conf /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/conf.d/prod/upstream.conf /etc/nginx/conf.d/upstream.conf
COPY ./docker/nginx/snippets/prod/snippets.conf /etc/nginx/snippets/snippets.conf

WORKDIR /var/www/ieducar

COPY public /var/www/ieducar/public

RUN chmod -R 755 /var/www/ieducar && \
    chown -R nginx:nginx /var/www/ieducar

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
