FROM node:20-alpine AS assets
WORKDIR /app

COPY package.json yarn.lock vite.config.js ./
COPY resources ./resources
COPY public ./public

ENV NODE_ENV=production
RUN yarn install --frozen-lockfile
RUN yarn run build

FROM nginx:1.28-alpine

COPY ./docker/nginx/conf.d/prod/default.conf /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/snippets/prod/snippets.conf /etc/nginx/snippets/snippets.conf

WORKDIR /var/www/ieducar

COPY --from=assets /app/public/build /var/www/ieducar/public/build

RUN chmod -R 755 /var/www/ieducar && \
    chown -R nginx:nginx /var/www/ieducar

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
